
var packagingTypes=[],globalAttributes=[],selectedAttributes=[],variations=[];
function defaultPackagingTypes(){return[{id:'pkt',name:'Packet',qty:1,cost_price:0,selling_price:0,item_number:'',default_sale:true,default_receiving:false},{id:'strip',name:'Strip',qty:10,cost_price:0,selling_price:0,item_number:'',default_sale:false,default_receiving:false},{id:'bottle',name:'Bottle',qty:1,cost_price:0,selling_price:0,item_number:'',default_sale:false,default_receiving:false},{id:'carton',name:'Carton',qty:1,cost_price:0,selling_price:0,item_number:'',default_sale:false,default_receiving:true},{id:'tube',name:'Tube',qty:1,cost_price:0,selling_price:0,item_number:'',default_sale:false,default_receiving:false},{id:'box',name:'Box',qty:1,cost_price:0,selling_price:0,item_number:'',default_sale:false,default_receiving:false},{id:'sachet',name:'Sachet',qty:1,cost_price:0,selling_price:0,item_number:'',default_sale:false,default_receiving:false},{id:'jar',name:'Jar',qty:1,cost_price:0,selling_price:0,item_number:'',default_sale:false,default_receiving:false},{id:'can',name:'Can',qty:1,cost_price:0,selling_price:0,item_number:'',default_sale:false,default_receiving:false},{id:'pcs',name:'Piece / Unit',qty:1,cost_price:0,selling_price:0,item_number:'',default_sale:false,default_receiving:false}];}
function getPackagingTypes(){try{var saved=JSON.parse(localStorage.getItem('packagingTypes')||'[]');return Array.isArray(saved)&&saved.length?saved:defaultPackagingTypes();}catch(e){return defaultPackagingTypes();}}
function savePackagingStorage(){localStorage.setItem('packagingTypes',JSON.stringify(packagingTypes));}
function loadDraft(){try{var d=JSON.parse(localStorage.getItem('productVariationDraft')||'{}');packagingTypes=getPackagingTypes();globalAttributes=Array.isArray(d.globalAttributes)?d.globalAttributes:[];selectedAttributes=Array.isArray(d.selectedAttributes)?d.selectedAttributes:[];variations=Array.isArray(d.variations)?d.variations:[];}catch(e){packagingTypes=getPackagingTypes();globalAttributes=[];selectedAttributes=[];variations=[]}renderAll();}
function saveDraft(){localStorage.setItem('productVariationDraft',JSON.stringify({globalAttributes:globalAttributes,selectedAttributes:selectedAttributes,variations:variations}));POS.showToast('Variation setup saved');}
function renderAll(){renderPackaging();renderGlobalAttributes();renderSelectedAttributes();renderVariations();}
function renderPackaging(){var body=$('packagingBody');if(!packagingTypes.length){body.innerHTML='<tr><td colspan="8" class="empty-state">No packaging types added</td></tr>';return;}body.innerHTML=packagingTypes.map(function(p,i){return '<tr><td>'+POS.esc(p.name)+'</td><td>'+POS.formatNumber(p.qty||1)+'</td><td>'+POS.formatCurrency(p.cost_price||0)+'</td><td>'+POS.formatCurrency(p.selling_price||0)+'</td><td>'+POS.esc(p.item_number||'-')+'</td><td class="checkbox-cell"><input type="checkbox" '+(p.default_sale?'checked':'')+' onchange="setPackagingDefault('+i+',"sale",this.checked)"></td><td class="checkbox-cell"><input type="checkbox" '+(p.default_receiving?'checked':'')+' onchange="setPackagingDefault('+i+',"receiving",this.checked)"></td><td class="action-btns"><button class="icon-btn edit" onclick="openPackagingModal('+i+')"><i class="fas fa-edit"></i></button><button class="icon-btn delete" onclick="deletePackagingType('+i+')"><i class="fas fa-trash"></i></button></td></tr>';}).join('');}
function renderGlobalAttributes(){var select=$('attributeSelect');select.innerHTML='<option value="">Select an Attribute</option>';globalAttributes.forEach(function(a,i){select.innerHTML+='<option value="'+i+'">'+POS.esc(a.name)+' ('+POS.esc((a.values||[]).join(', '))+')</option>';});}
function renderSelectedAttributes(){var body=$('attributeBody');if(!selectedAttributes.length){body.innerHTML='<tr><td colspan="3" class="empty-state">No attributes selected for this product</td></tr>';return;}body.innerHTML=selectedAttributes.map(function(a,i){return '<tr><td>'+POS.esc(a.name)+'</td><td>'+POS.esc((a.values||[]).join(', '))+'</td><td class="action-btns"><button class="icon-btn delete" onclick="deleteSelectedAttribute('+i+')"><i class="fas fa-trash"></i></button></td></tr>';}).join('');}
function renderVariations(){var body=$('variationBody');if(!variations.length){body.innerHTML='<tr><td colspan="6" class="empty-state">No item variations added</td></tr>';return;}body.innerHTML=variations.map(function(v,i){return '<tr><td>'+POS.esc(v.name)+'</td><td>'+POS.esc(v.attributes)+'</td><td>'+POS.esc(v.item_number||'-')+'</td><td class="checkbox-cell"><input type="checkbox" '+(v.ecommerce?'checked':'')+' onchange="setVariationEcommerce('+i+',this.checked)"></td><td>'+POS.esc(v.supplier||'-')+'</td><td class="action-btns"><button class="icon-btn edit" onclick="openVariationModal('+i+')"><i class="fas fa-edit"></i></button><button class="icon-btn delete" onclick="deleteVariation('+i+')"><i class="fas fa-trash"></i></button></td></tr>';}).join('');}
function openPackagingModal(idx){var p=idx===undefined?null:packagingTypes[idx];$('packagingModalTitle').textContent=p?'Edit Packaging Type':'Add Packaging Type';$('packagingIndex').value=p?idx:'';$('packagingName').value=p?p.name:'';$('packagingQty').value=p?p.qty||1:1;$('packagingCost').value=p?p.cost_price||0:0;$('packagingSell').value=p?p.selling_price||0:0;$('packagingItemNumber').value=p?p.item_number||'';$('packagingDefaultSale').checked=!!(p&&p.default_sale);$('packagingDefaultReceive').checked=!!(p&&p.default_receiving);POS.openModal('packagingModal');}
function closePackagingModal(){POS.closeModal('packagingModal');}
function savePackagingType(){var idx=$('packagingIndex').value,name=$('packagingName').value.trim();if(!name){POS.showToast('Packaging name is required',true);return;}var item={name:name,qty:parseInt($('packagingQty').value)||1,cost_price:parseFloat($('packagingCost').value)||0,selling_price:parseFloat($('packagingSell').value)||0,item_number:$('packagingItemNumber').value.trim(),default_sale:!!$('packagingDefaultSale').checked,default_receiving:!!$('packagingDefaultReceive').checked};if(idx===''){packagingTypes.push(item);}else{packagingTypes[idx]=item;}if(packagingTypes.filter(function(p){return p.default_sale;}).length>1){packagingTypes.forEach(function(p){if(p!==item)p.default_sale=false;});}if(packagingTypes.filter(function(p){return p.default_receiving;}).length>1){packagingTypes.forEach(function(p){if(p!==item)p.default_receiving=false;});}closePackagingModal();renderPackaging();savePackagingStorage();saveDraft();}
function deletePackagingType(idx){if(!confirm('Delete this packaging type?'))return;packagingTypes.splice(idx,1);renderPackaging();savePackagingStorage();saveDraft();}
function setPackagingDefault(idx,type,value){packagingTypes[idx][type==='sale'?'default_sale':'default_receiving']=value;if(value){packagingTypes.forEach(function(p,i){if(i!==idx)p[type==='sale'?'default_sale':'default_receiving']=false;});}renderPackaging();savePackagingStorage();saveDraft();}
function addSelectedAttribute(){var idx=$('attributeSelect').value;if(idx===''){POS.showToast('Select an attribute',true);return;}var attr=globalAttributes[parseInt(idx)];if(!attr)return;if(selectedAttributes.some(function(a){return a.name===attr.name;})){POS.showToast('Attribute already added',true);return;}selectedAttributes.push({name:attr.name,values:[].slice.call(attr.values||[])});renderSelectedAttributes();}
function deleteSelectedAttribute(idx){selectedAttributes.splice(idx,1);renderSelectedAttributes();}
function openVariationModal(idx){var v=idx===undefined?null:variations[idx];$('variationModalTitle').textContent=v?'Edit Item Variation':'Add Item Variation';$('variationIndex').value=v?idx:'';$('variationName').value=v?v.name:'';$('variationAttributes').value=v?v.attributes:'';$('variationItemNumber').value=v?v.item_number||'';$('variationSupplier').value=v?v.supplier||'';$('variationEcommerce').checked=!!(v&&v.ecommerce);POS.openModal('variationModal');}
function closeVariationModal(){POS.closeModal('variationModal');}
function saveVariation(){var idx=$('variationIndex').value,name=$('variationName').value.trim();if(!name){POS.showToast('Variation name is required',true);return;}var item={name:name,attributes:$('variationAttributes').value.trim(),item_number:$('variationItemNumber').value.trim(),supplier:$('variationSupplier').value.trim(),ecommerce:!!$('variationEcommerce').checked};if(idx===''){variations.push(item);}else{variations[idx]=item;}closeVariationModal();renderVariations();saveDraft();}
function deleteVariation(idx){if(!confirm('Delete this item variation?'))return;variations.splice(idx,1);renderVariations();saveDraft();}
function setVariationEcommerce(idx,value){variations[idx].ecommerce=value;saveDraft();}
function openGlobalAttributeModal(){renderGlobalAttributeBody();POS.openModal('globalAttributeModal');setTimeout(function(){$('globalAttributeName').focus();},50);}
function closeGlobalAttributeModal(){POS.closeModal('globalAttributeModal');}
function renderGlobalAttributeBody(){var body=$('globalAttributeBody');if(!globalAttributes.length){body.innerHTML='<tr><td colspan="3" class="empty-state">No global attributes saved</td></tr>';return;}body.innerHTML=globalAttributes.map(function(a,i){return '<tr><td>'+POS.esc(a.name)+'</td><td>'+POS.esc((a.values||[]).join(', '))+'</td><td class="action-btns"><button class="icon-btn edit" onclick="loadGlobalAttribute('+i+')"><i class="fas fa-edit"></i></button><button class="icon-btn delete" onclick="deleteGlobalAttribute('+i+')"><i class="fas fa-trash"></i></button></td></tr>';}).join('');}
function saveGlobalAttribute(){var name=$('globalAttributeName').value.trim(),values=$('globalAttributeValues').value.split(',').map(function(v){return v.trim();}).filter(function(v){return v;});if(!name||!values.length){POS.showToast('Attribute name and values are required',true);return;}var existing=globalAttributes.findIndex(function(a){return a.name.toLowerCase()===name.toLowerCase();});var item={name:name,values:values};if(existing>-1){globalAttributes[existing]=item;selectedAttributes.forEach(function(a){if(a.name.toLowerCase()===name.toLowerCase())a.values=values;});}else{globalAttributes.push(item);}$('globalAttributeName').value='';$('globalAttributeValues').value='';renderGlobalAttributes();renderGlobalAttributeBody();renderSelectedAttributes();saveDraft();}
function loadGlobalAttribute(idx){var a=globalAttributes[idx];if(!a)return;$('globalAttributeName').value=a.name;$('globalAttributeValues').value=(a.values||[]).join(', ');}
function deleteGlobalAttribute(idx){if(!confirm('Delete this global attribute?'))return;globalAttributes.splice(idx,1);renderGlobalAttributes();renderGlobalAttributeBody();renderSelectedAttributes();saveDraft();}
document.addEventListener('DOMContentLoaded',function(){if(!POS.requireAuth())return;POS.renderSidebar();POS.renderUserMenu();loadDraft();});
